### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by ANU8151** [MZanggl/inertia-adonis#2]
Can you update this adapter

![Capture](https://user-images.githubusercontent.com/26343845/67070807-0f8e1600-f192-11e9-8e25-7d0787ab21b7.PNG)

**Comment by MZanggl** [comment]
Thanks for the issue!

If you need it soon, could you raise a PR for it?

**Comment by MZanggl** [comment]
I updated the dependencies and published a new version on npm.
